name: Lint code

defaults:
  run:
    working-directory: backend
    shell: bash

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: ./.github/actions/setup-backend
    - run: isort . -c
    - run: black . --check
    - run: flake8 . --max-line-length=88 --ignore=T484,T499,D100,D101,D102,D103,D104,D105,D107,W503 --exclude=__pycache__,*migrations*,settings.py
    - name: Running mypy
      run: mypy . --strict
