name: Install Backend Dependencies

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    
    - name: Install requirements
      run: pip install -r ./backend/requirements.txt
