version: "3"

services:
  proxy:
    image: "traefik:v3.0"
    container_name: "proxy"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik_proxy
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL=${CF_EMAIL}
    volumes:
      - "./traefik.prod.yaml:/traefik.yaml:ro"
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik_proxy:
    external: true
