"""add schedule

Revision ID: 70412556ca33
Revises: b9f8b7b0fcb6
Create Date: 2023-09-29 21:58:05.687651

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "70412556ca33"
down_revision = "b9f8b7b0fcb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("search", sa.Column("schedule", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("search", "schedule")
    # ### end Alembic commands ###
