"""add url

Revision ID: b9f8b7b0fcb6
Revises: efbeab290ccc
Create Date: 2023-09-18 23:23:28.354842

"""
import random

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9f8b7b0fcb6"
down_revision = "efbeab290ccc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "search", sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_index(op.f("ix_search_url"), "search", ["url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_url"), table_name="search")
    op.drop_column("search", "url")
    # ### end Alembic commands ###
