"""modify user model

Revision ID: e8a730aa8d16
Revises: 70412556ca33
Create Date: 2023-12-24 19:04:28.257476

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8a730aa8d16"
down_revision = "70412556ca33"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("roles", sa.JSON(), nullable=True))
    op.add_column(
        "user",
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    op.drop_column("user", "password")
    op.drop_column("user", "roles")
    # ### end Alembic commands ###
